### ISSUE TITLE
StepmotorPulse_M039.ino did not work

### ISSUE THREAD

**Issue by takashiyamanoue** [m5stack/MODULE_DIRECT_STEPMOTOR#1]
I got the M5Stack's Stepmotor Driver Module13.2 v1.1 (https://docs.m5stack.com/en/module/Stepmotor%20Driver%20Module13.2%20v1.1 ), and I reached this github page.
I've tried to run the StepmotorPulse_M03i.ino, but there were syntax errors.
So, I replaced the "DIRCT_STEPMOTOR::" by the "Module_Stepmotor::", and the compile was succeeded.
However, when I ran the program, the step motor did not rotate. Instead of the rotating, I heard a sound from the motor.

I've also tried the UIflow example in the https://docs.m5stack.com/en/module/Stepmotor%20Driver%20Module13.2%20v1.1, the UIflow example ran correctly.

I'd like to use arduino IDE for the stepmotor driver modue. Is there any solution?

**Comment by FyrbyAdditive** [comment]
It's hard to learn when the only example is broken. Sadly we will send our boards back as they are not fit for purpose if we can not use them.

**Comment by FyrbyAdditive** [comment]
It would also be very nice if there could be some comments in the example code and the cpp file it includes also, thank you.

**Comment by TinyuZhao** [comment]
Sorry for the inconvenience. I fixed it.
